### ISSUE TITLE
CodeXGLUE dataset

### ISSUE THREAD

**Issue by ramsey-coding** [iCSawyer/CodeSuggestion#6]
In the paper, it is mentioned that CodeXGLUE dataset was used.

However, the number of train/test datapoint instances are not matching up.

From where have you taken the dataset from?

I presume https://github.com/microsoft/CodeXGLUE/tree/main/Text-Code/NL-code-search-Adv?

Data Statistics from this dataset:

Data statistics of the dataset are shown in the below table:

|       | #Examples |
| ----- | :-------: |
| Train |  251,820  |
| Dev   |   9,604   |
| Test  |  19,210   |

However, it does not match up with what is reported in the paper:

CodeXGLUE
For Java, methods in test: 10,729

Please help.

**Comment by ramsey-coding** [comment]
Alternately, can you please refer to me which dataset are you using if it is also available here?
https://huggingface.co/datasets?search=code_x_glue

**Comment by iCSawyer** [comment]
Hi! This is the dataset we use: https://github.com/microsoft/CodeXGLUE/tree/main/Code-Text/code-to-text, and I think it is the same as https://huggingface.co/datasets/code_x_glue_ct_code_to_text. The statistics of the dataset are different from CodeXGLUE because we further filter some data because of the data overlap as is mentioned in sec 4.3.2.
